/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplychaintrackingsystem;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author zeina
 */
public class CustomerGUI extends javax.swing.JFrame {

    /**
     * Creates new form CustomerGUI
     */
    public CustomerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CustomerID = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        btnAddCustomer = new javax.swing.JButton();
        btnViewOrders = new javax.swing.JButton();
        btnTrackOrder = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Customer ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Product Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Quantity:");

        CustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerIDActionPerformed(evt);
            }
        });

        txtProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNameActionPerformed(evt);
            }
        });

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        btnAddCustomer.setBackground(new java.awt.Color(76, 175, 80));
        btnAddCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddCustomer.setForeground(new java.awt.Color(242, 242, 242));
        btnAddCustomer.setText("Create Order");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnViewOrders.setBackground(new java.awt.Color(33, 150, 243));
        btnViewOrders.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewOrders.setForeground(new java.awt.Color(242, 242, 242));
        btnViewOrders.setText("View Orders");
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersActionPerformed(evt);
            }
        });

        btnTrackOrder.setBackground(new java.awt.Color(156, 39, 176));
        btnTrackOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTrackOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnTrackOrder.setText("TrackOrder");
        btnTrackOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackOrderActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 152, 0));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(242, 242, 242));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(158, 158, 158));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Customer Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(242, 242, 242));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTrackOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCustomer)
                    .addComponent(btnBack)
                    .addComponent(btnViewOrders)
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnTrackOrder))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
        try {

        if (CustomerID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter Customer ID first");
            return;
        }

        int customerId =
        Integer.parseInt(CustomerID.getText().trim());

        Connection con = DBConnection.connect();

        String sql =
        "SELECT o.order_id, o.order_date, o.status, o.total_amount, " +
        "p.product_name, oi.quantity, oi.price " +
        "FROM orders o " +
        "JOIN order_items oi ON o.order_id = oi.order_id " +
        "JOIN products p ON oi.product_id = p.product_id " +
        "WHERE o.customer_id = ? " +
        "ORDER BY o.order_id DESC";

        PreparedStatement ps = con.prepareStatement(sql);

        ps.setInt(1, customerId);

        ResultSet rs = ps.executeQuery();

        String data = "";

        while (rs.next()) {

            data += "Order ID: " + rs.getInt("order_id")
                 + "\nDate: " + rs.getString("order_date")
                 + "\nStatus: " + rs.getString("status")
                 + "\nProduct: " + rs.getString("product_name")
                 + "\nQuantity: " + rs.getInt("quantity")
                 + "\nPrice: " + rs.getDouble("price")
                 + "\nTotal: " + rs.getDouble("total_amount")
                 + "\n--------------------------\n";
        }

        if (data.equals("")) {

            JOptionPane.showMessageDialog(this,
                    "You do not have previous orders");

        } else {

            JOptionPane.showMessageDialog(this,
                    data,
                    "Previous Orders",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        con.close();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Customer ID must be a number");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
    
    }//GEN-LAST:event_btnViewOrdersActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose(); 
       new LoginGuii().setVisible(true);
    
    }//GEN-LAST:event_btnBackActionPerformed

    private void CustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerIDActionPerformed
 try {

        if (CustomerID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter Customer ID first");
            return;
        }

        int customerId =
        Integer.parseInt(CustomerID.getText().trim());

        Connection con = DBConnection.connect();

        String sql =
        "SELECT customer_id FROM orders WHERE customer_id = ? LIMIT 1";

        PreparedStatement ps =
        con.prepareStatement(sql);

        ps.setInt(1, customerId);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            JOptionPane.showMessageDialog(this,
                    "Customer ID found");

        } else {

            JOptionPane.showMessageDialog(this,
                    "Customer ID not found");
        }

        con.close();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Customer ID must be a number");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
    }//GEN-LAST:event_CustomerIDActionPerformed

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
       try {

        if (txtProductName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter Product Name first");
            return;
        }

        String productName =
        txtProductName.getText().trim();

        Connection con = DBConnection.connect();

        String sql =
        "SELECT unit_price, stock_quantity " +
        "FROM products WHERE product_name = ?";

        PreparedStatement ps =
        con.prepareStatement(sql);

        ps.setString(1, productName);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            JOptionPane.showMessageDialog(this,
                    "Product Found"
                    + "\nName: " + productName
                    + "\nPrice: " + rs.getDouble("unit_price")
                    + "\nStock: " + rs.getInt("stock_quantity"));

        } else {

            JOptionPane.showMessageDialog(this,
                    "Product not found");
        }

        con.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
      
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
          try {

        if (txtProductName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter Product Name first");
            return;
        }

        if (txtQuantity.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter Quantity");
            return;
        }

        int quantity =
        Integer.parseInt(txtQuantity.getText().trim());

        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Quantity must be greater than 0");
            txtQuantity.setText("");
            return;
        }

        String productName =
        txtProductName.getText().trim();

        Connection con = DBConnection.connect();

        String sql =
        "SELECT stock_quantity, unit_price " +
        "FROM products WHERE product_name = ?";

        PreparedStatement ps =
        con.prepareStatement(sql);

        ps.setString(1, productName);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            int stock =
            rs.getInt("stock_quantity");

            double price =
            rs.getDouble("unit_price");

            if (quantity > stock) {

                JOptionPane.showMessageDialog(this,
                        "Only " + stock + " items available");

            } else {

                double total = quantity * price;

                JOptionPane.showMessageDialog(this,
                        "Available"
                        + "\nTotal Price: " + total);
            }

        } else {

            JOptionPane.showMessageDialog(this,
                    "Product not found");
        }

        con.close();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Quantity must be a number");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
      try {

        if (CustomerID.getText().trim().isEmpty()
                || txtProductName.getText().trim().isEmpty()
                || txtQuantity.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Please fill all fields first");
            return;
        }

        int customerId =
        Integer.parseInt(CustomerID.getText().trim());

        String productName =
        txtProductName.getText().trim();

        int quantity =
        Integer.parseInt(txtQuantity.getText().trim());

        Connection con = DBConnection.connect();

        String sql =
        "SELECT product_id, unit_price, stock_quantity " +
        "FROM products WHERE product_name = ?";

        PreparedStatement ps =
        con.prepareStatement(sql);

        ps.setString(1, productName);

        ResultSet rs = ps.executeQuery();

        if (!rs.next()) {
            JOptionPane.showMessageDialog(this,
                    "Product not found");
            return;
        }

        int productId = rs.getInt("product_id");
        double price = rs.getDouble("unit_price");
        int stock = rs.getInt("stock_quantity");

        if (quantity > stock) {
            JOptionPane.showMessageDialog(this,
                    "Not enough stock");
            return;
        }

        double total = quantity * price;

        PreparedStatement ps2 =
        con.prepareStatement(
        "INSERT INTO orders(customer_id,status,total_amount) VALUES(?,?,?)",
        Statement.RETURN_GENERATED_KEYS);

        ps2.setInt(1, customerId);
        ps2.setString(2, "Pending");
        ps2.setDouble(3, total);

        ps2.executeUpdate();

        ResultSet keys = ps2.getGeneratedKeys();

        int orderId = 0;

        if (keys.next()) {
            orderId = keys.getInt(1);
        }

        PreparedStatement ps3 =
        con.prepareStatement(
        "INSERT INTO order_items(order_id,product_id,quantity,price) VALUES(?,?,?,?)");

        ps3.setInt(1, orderId);
        ps3.setInt(2, productId);
        ps3.setInt(3, quantity);
        ps3.setDouble(4, price);

        ps3.executeUpdate();

        PreparedStatement ps4 =
        con.prepareStatement(
        "UPDATE products SET stock_quantity = stock_quantity - ? WHERE product_id=?");

        ps4.setInt(1, quantity);
        ps4.setInt(2, productId);

        ps4.executeUpdate();

        JOptionPane.showMessageDialog(this,
                "Order Created Successfully"
                + "\nOrder ID: " + orderId
                + "\nTotal: " + total);

        con.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnTrackOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackOrderActionPerformed
        try {

        if (CustomerID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter Customer ID first");
            return;
        }

        int customerId =
        Integer.parseInt(CustomerID.getText().trim());

        Connection con = DBConnection.connect();

        String sql =
        "SELECT o.order_id, o.order_date, o.status, o.total_amount, " +
        "p.product_name, oi.quantity " +
        "FROM orders o " +
        "JOIN order_items oi ON o.order_id = oi.order_id " +
        "JOIN products p ON oi.product_id = p.product_id " +
        "WHERE o.customer_id = ? " +
        "ORDER BY o.order_id DESC LIMIT 1";

        PreparedStatement ps =
        con.prepareStatement(sql);

        ps.setInt(1, customerId);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            JOptionPane.showMessageDialog(this,
                    "Latest Order Tracking"
                    + "\nOrder ID: " + rs.getInt("order_id")
                    + "\nDate: " + rs.getString("order_date")
                    + "\nProduct: " + rs.getString("product_name")
                    + "\nQuantity: " + rs.getInt("quantity")
                    + "\nStatus: " + rs.getString("status")
                    + "\nTotal: " + rs.getDouble("total_amount"));

        } else {

            JOptionPane.showMessageDialog(this,
                    "No orders found for this customer");
        }

        con.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }

    }//GEN-LAST:event_btnTrackOrderActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
      
    if (CustomerID.getText().trim().isEmpty()
            && txtProductName.getText().trim().isEmpty()
            && txtQuantity.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "There is nothing to clear");
        return;
    }

    CustomerID.setText("");
    txtProductName.setText("");
    txtQuantity.setText("");

    CustomerID.requestFocus();

    JOptionPane.showMessageDialog(this,
            "Fields cleared");


    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    
        try {

    if (CustomerID.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Please enter Customer ID first");
        return;
    }

    int customerId =
    Integer.parseInt(CustomerID.getText().trim());

    Connection con = DBConnection.connect();

    PreparedStatement check =
    con.prepareStatement(
    "SELECT order_id FROM orders WHERE customer_id=? ORDER BY order_id DESC LIMIT 1");

    check.setInt(1, customerId);

    ResultSet rs = check.executeQuery();

    if (!rs.next()) {
        JOptionPane.showMessageDialog(this,
                "No orders found for this customer");
        con.close();
        return;
    }

    int orderId = rs.getInt("order_id");

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Delete latest order ID " + orderId + " ?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        con.close();
        return;
    }

    PreparedStatement ps1 =
    con.prepareStatement(
    "DELETE FROM order_items WHERE order_id=?");

    ps1.setInt(1, orderId);
    ps1.executeUpdate();

    PreparedStatement ps2 =
    con.prepareStatement(
    "DELETE FROM orders WHERE order_id=?");

    ps2.setInt(1, orderId);

    int rows = ps2.executeUpdate();

    if (rows > 0) {

        JOptionPane.showMessageDialog(this,
                "Order deleted successfully");

        CustomerID.setText("");
        txtProductName.setText("");
        txtQuantity.setText("");

    } else {

        JOptionPane.showMessageDialog(this,
                "Delete failed");
    }

    con.close();

} catch (Exception e) {

    JOptionPane.showMessageDialog(this,
            e.getMessage());
}
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustomerID;
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTrackOrder;
    private javax.swing.JButton btnViewOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
