/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplychaintrackingsystem;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;





/**
 *
 * @author M-ABEER
 */
public class Distributor_GUI extends javax.swing.JFrame {
private Distributor currentDistributor;
private final List<String> distributorRecords = new ArrayList<>();
    /**
     * Creates new form Distributor_GUI
     */
     
public Distributor_GUI() {
    initComponents();
    configureDefaults();
    populateDistributorProfile();
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewShipments = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        ReportIssue = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtProductID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtShipmentID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Origin = new javax.swing.JTextField();
        Destination = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        RegulatorID = new javax.swing.JLabel();
        AgencyName = new javax.swing.JLabel();
        AccessLevel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DistributorID = new javax.swing.JTextField();
        FullName = new javax.swing.JTextField();
        ContactNumber = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Area = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReceiveProducts = new javax.swing.JButton();
        btnSendProducts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnViewShipments.setBackground(new java.awt.Color(0, 172, 193));
        btnViewShipments.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewShipments.setForeground(new java.awt.Color(242, 242, 242));
        btnViewShipments.setText("View Shipments");
        btnViewShipments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewShipmentsActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(158, 158, 158));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(242, 242, 242));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        ReportIssue.setBackground(new java.awt.Color(204, 0, 204));
        ReportIssue.setForeground(new java.awt.Color(242, 242, 242));
        ReportIssue.setText("Report Issue");
        ReportIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportIssueActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(96, 125, 139));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(242, 242, 242));
        btnBack.setText("Back       ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Distributor Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 153, 51))); // NOI18N

        txtProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Product ID");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Shipment ID");

        txtShipmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShipmentIDActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Origin:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Destination:");

        Origin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OriginActionPerformed(evt);
            }
        });

        Destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtProductID, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(txtShipmentID)
                        .addComponent(Origin))
                    .addComponent(Destination, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtShipmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(Origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(Destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Distributor Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        RegulatorID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegulatorID.setText("Distributor ID");

        AgencyName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgencyName.setText("Full Name");

        AccessLevel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AccessLevel.setText("Email");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Contact Number");

        DistributorID.setEditable(false);

        FullName.setEditable(false);

        ContactNumber.setEditable(false);

        Email.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Distribution Area:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Status:");

        Area.setEditable(false);
        Area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaActionPerformed(evt);
            }
        });

        Status.setEditable(false);
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegulatorID)
                            .addComponent(AgencyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FullName, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(DistributorID))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Area)
                                    .addComponent(Status)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegulatorID)
                    .addComponent(DistributorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgencyName)
                    .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccessLevel)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Distributor Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        btnReceiveProducts.setBackground(new java.awt.Color(76, 175, 80));
        btnReceiveProducts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReceiveProducts.setForeground(new java.awt.Color(242, 242, 242));
        btnReceiveProducts.setText(" Receive Products");
        btnReceiveProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiveProductsActionPerformed(evt);
            }
        });

        btnSendProducts.setBackground(new java.awt.Color(255, 152, 0));
        btnSendProducts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSendProducts.setForeground(new java.awt.Color(242, 242, 242));
        btnSendProducts.setText("Send Products");
        btnSendProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnReceiveProducts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSendProducts))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewShipments)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ReportIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnClear)
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReceiveProducts)
                    .addComponent(btnSendProducts)
                    .addComponent(btnViewShipments)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(ReportIssue))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewShipmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewShipmentsActionPerformed
    try {
        int shipmentID = parseRequiredInt(txtShipmentID.getText(), "Shipment ID");

        Connection con = DBConnection.connect();

        String sql = "SELECT * FROM shipments WHERE shipment_id=?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, shipmentID);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            String message =
                    "Shipment Details\n\n"
                    + "Shipment ID: " + rs.getInt("shipment_id") + "\n"
                    + "Order ID: " + rs.getInt("order_id") + "\n"
                    + "Origin: " + rs.getString("origin") + "\n"
                    + "Destination: " + rs.getString("destination") + "\n"
                    + "Current Location: " + rs.getString("current_location") + "\n"
                    + "Status: " + rs.getString("status");

            JOptionPane.showMessageDialog(this,
                    message,
                    "View Shipments",
                    JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this,
                    "Shipment not found.");
        }

        rs.close();
        ps.close();
        con.close();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnViewShipmentsActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
   txtProductID.setText("");
    txtShipmentID.setText("");
    Origin.setText("");
    Destination.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void ReportIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportIssueActionPerformed
       try {
        int shipmentID = parseRequiredInt(txtShipmentID.getText(), "Shipment ID");

        String issue = JOptionPane.showInputDialog(this, "Enter shipment issue:");

        if (issue == null || issue.trim().isEmpty()) {
            throw new IllegalArgumentException("Issue cannot be empty.");
        }

        Connection con = DBConnection.connect();

        String sql = "INSERT INTO support_requests (customer_id, message, status) VALUES (?, ?, ?)";

        PreparedStatement ps = con.prepareStatement(sql);

        ps.setInt(1, Integer.parseInt(DistributorID.getText()));  
        ps.setString(2, "Shipment ID: " + shipmentID + " - " + issue);
        ps.setString(3, "OPEN");

        ps.executeUpdate();

        ps.close();
        con.close();

        JOptionPane.showMessageDialog(this,
                "Issue saved in support_requests successfully.");

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_ReportIssueActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
            try {
        new LoginGuii().setVisible(true);
        dispose();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unable to return to login page: " + ex.getMessage(),
                "Navigation Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIDActionPerformed

    private void txtShipmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShipmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShipmentIDActionPerformed

    private void OriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OriginActionPerformed
        
    }//GEN-LAST:event_OriginActionPerformed

    private void DestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationActionPerformed
        
    }//GEN-LAST:event_DestinationActionPerformed

    private void AreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaActionPerformed
        
    }//GEN-LAST:event_AreaActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        
    }//GEN-LAST:event_StatusActionPerformed

    private void btnReceiveProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiveProductsActionPerformed
      try {
        int productID = parseRequiredInt(txtProductID.getText(), "Product ID");
        int shipmentID = parseRequiredInt(txtShipmentID.getText(), "Shipment ID");

        Shipment shipment = createLocalShipmentIfNeeded(shipmentID);

        shipment.receiveShipment(shipmentID);
        currentDistributor.addShipment(shipment);

        String record =
                "Products Received Successfully\n"
                + "Distributor ID: " + currentDistributor.getUserID() + "\n"
                + "Product ID: " + productID + "\n"
                + "Shipment ID: " + shipmentID + "\n"
                + "Shipment Status: " + shipment.getStatus();

        distributorRecords.add(record);

        JOptionPane.showMessageDialog(this,
                record,
                "Receive Products",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException | IllegalStateException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while receiving products: " + ex.getMessage(),
                "Distributor Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnReceiveProductsActionPerformed

    private void btnSendProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendProductsActionPerformed
         try {
        int productID = parseRequiredInt(txtProductID.getText(), "Product ID");
        int shipmentID = parseRequiredInt(txtShipmentID.getText(), "Shipment ID");
        String origin = readRequiredText(Origin.getText(), "Origin");
        String destination = readRequiredText(Destination.getText(), "Destination");

        Connection con = DBConnection.connect();

        String checkSql = "SELECT shipment_id FROM shipments WHERE shipment_id=?";
        PreparedStatement checkPs = con.prepareStatement(checkSql);
        checkPs.setInt(1, shipmentID);
        ResultSet rs = checkPs.executeQuery();

        if (rs.next()) {
            String updateSql = "UPDATE shipments SET origin=?, destination=?, status='IN_TRANSIT', current_location=? WHERE shipment_id=?";
            PreparedStatement ps = con.prepareStatement(updateSql);
            ps.setString(1, origin);
            ps.setString(2, destination);
            ps.setString(3, origin);
            ps.setInt(4, shipmentID);
            ps.executeUpdate();
            ps.close();
        } else {
            String insertSql = "INSERT INTO shipments (shipment_id, order_id, origin, destination, current_location, status) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(insertSql);
            ps.setInt(1, shipmentID);
            ps.setInt(2, productID);
            ps.setString(3, origin);
            ps.setString(4, destination);
            ps.setString(5, origin);
            ps.setString(6, "IN_TRANSIT");
            ps.executeUpdate();
            ps.close();
        }

        rs.close();
        checkPs.close();
        con.close();

        JOptionPane.showMessageDialog(this,
                "Shipment saved successfully in database.",
                "Send Products",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSendProductsActionPerformed
private void configureDefaults() {
    txtProductID.setText("");
    txtShipmentID.setText("");
    Origin.setText("");
    Destination.setText("");

    DistributorID.setText("");
    FullName.setText("");
    Email.setText("");
    ContactNumber.setText("");
    Area.setText("");
    Status.setText("");
}

private void populateDistributorProfile() {
    try {
        User currentUser = AppContext.getCurrentUser();

        if (currentUser == null) {
            JOptionPane.showMessageDialog(this, "No logged in user found");
            return;
        }

        Connection con = DBConnection.connect();

        String sql = "SELECT * FROM users WHERE user_id=? AND role='Distributor'";

        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, currentUser.getUserID());

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            DistributorID.setText(rs.getString("user_id"));
            FullName.setText(rs.getString("full_name"));
            Email.setText(rs.getString("email"));
            ContactNumber.setText("0100000000");

            Area.setText(rs.getString("distribution_area"));
            Status.setText(rs.getString("status"));

            currentDistributor = new Distributor(
                rs.getInt("user_id"),
                rs.getString("full_name"),
                rs.getString("email"),
                rs.getString("password"),
                rs.getString("role"),
                rs.getString("distribution_area")
            );

        } else {
            JOptionPane.showMessageDialog(this, "Distributor data not found");
        }

        rs.close();
        ps.close();
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

    DistributorID.setText(String.valueOf(currentDistributor.getUserID()));
    FullName.setText(currentDistributor.getName());
    Email.setText(currentDistributor.getEmail());
    ContactNumber.setText("01000000000");
    Area.setText(currentDistributor.getWarehouseLocation());
    Status.setText("Active");
}


private Shipment createLocalShipmentIfNeeded(int shipmentID) {
    Shipment existingShipment = findShipmentByID(shipmentID);

    if (existingShipment != null) {
        return existingShipment;
    }

    Shipment shipment = new Shipment(shipmentID);

    String origin = Origin.getText() == null || Origin.getText().trim().isEmpty()
            ? currentDistributor.getWarehouseLocation()
            : Origin.getText().trim();

    String destination = Destination.getText() == null || Destination.getText().trim().isEmpty()
            ? "Retailer Destination"
            : Destination.getText().trim();

    shipment.setOrigin(origin);
    shipment.setDestination(destination);
    shipment.setCurrentLocation(origin);
    shipment.setWeight(1.0);
    shipment.setDistance(1.0);

    currentDistributor.addShipment(shipment);

    return shipment;
}

private Shipment findShipmentByID(int shipmentID) {
    if (currentDistributor == null) {
        return null;
    }

    for (Shipment shipment : currentDistributor.getShipments()) {
        if (shipment.getShipmentID() == shipmentID) {
            return shipment;
        }
    }

    return null;
}

private int parseRequiredInt(String value, String fieldName) {
    String text = value == null ? "" : value.trim();

    if (text.isBlank()) {
        throw new IllegalArgumentException(fieldName + " cannot be empty.");
    }

    if (!text.matches("\\d+")) {
        throw new IllegalArgumentException(fieldName + " must contain numbers only.");
    }

    int number = Integer.parseInt(text);

    if (number <= 0) {
        throw new IllegalArgumentException(fieldName + " must be greater than 0.");
    }

    return number;
}

private String readRequiredText(String value, String fieldName) {
    String text = value == null ? "" : value.trim();

    if (text.isBlank()) {
        throw new IllegalArgumentException(fieldName + " cannot be empty.");
    }

    return text;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Distributor_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Distributor_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Distributor_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Distributor_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Distributor_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccessLevel;
    private javax.swing.JLabel AgencyName;
    private javax.swing.JTextField Area;
    private javax.swing.JTextField ContactNumber;
    private javax.swing.JTextField Destination;
    private javax.swing.JTextField DistributorID;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FullName;
    private javax.swing.JTextField Origin;
    private javax.swing.JLabel RegulatorID;
    private javax.swing.JButton ReportIssue;
    private javax.swing.JTextField Status;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnReceiveProducts;
    private javax.swing.JButton btnSendProducts;
    private javax.swing.JButton btnViewShipments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtShipmentID;
    // End of variables declaration//GEN-END:variables
}

