/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplychaintrackingsystem;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * 
 */
public class InventoryGUI extends javax.swing.JFrame {
    private final InventoryBoundary inventoryBoundary;
    private final Product productContext;

    
    private boolean validateFields() {

    if (
         txtProductID.getText().trim().isEmpty()
        || txtWarehouseLocation.getText().trim().isEmpty()
        || txtCurrentQuantity.getText().trim().isEmpty()
        || txtAddQuantity.getText().trim().isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please fill all Inventory Details and Stock Control fields.",
            "Missing Data",
            javax.swing.JOptionPane.WARNING_MESSAGE
        );

        return false;
    }

    return true;
}
    
    /**
     * Creates new form InventoryGUI
     */
    public InventoryGUI() {
        this(AppContext.inventoryBoundary(), null);
    }

    public InventoryGUI(InventoryBoundary inventoryBoundary) {
        this(inventoryBoundary, null);
    }

    public InventoryGUI(Product product) {
        this(AppContext.inventoryBoundary(), product);
    }

    public InventoryGUI(InventoryBoundary inventoryBoundary, Product product) {
        this.inventoryBoundary = inventoryBoundary == null ? AppContext.inventoryBoundary() : inventoryBoundary;
        this.productContext = product;
        initComponents();
        prefillFromProduct();
        txtLastUpdated.setEditable(false);
        txtLastUpdated.setFocusable(false);
    }
    
    
    private void loadInventoryByProductID(int productId) {

    try (Connection con = DBConnection.connect()) {

        String sql =
        "SELECT * FROM inventory WHERE product_id=?";

        PreparedStatement ps =
                con.prepareStatement(sql);

        ps.setInt(1, productId);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            txtProductID.setText(rs.getString("product_id"));
            txtWarehouseLocation.setText(
                    rs.getString("warehouse_location"));

            txtCurrentQuantity.setText(
                    rs.getString("quantity"));

            txtLastUpdated.setText(
                    rs.getString("last_updated"));

            cmbStockCondition.setSelectedItem(
                    rs.getString("stock_condition"));
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
}
    

    private boolean isEmpty(javax.swing.JTextField txt) {
    return txt.getText().trim().isEmpty();
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtProductID = new javax.swing.JTextField();
        txtWarehouseLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCurrentQuantity = new javax.swing.JTextField();
        txtAddQuantity = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtLastUpdated = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbStockCondition = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnAddStock = new javax.swing.JButton();
        btnUpdateStock = new javax.swing.JButton();
        btnDetectLowStock = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Inventory Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventory Item Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 0, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Product ID:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Warehouse Location:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(43, 43, 43)
                        .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtWarehouseLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtWarehouseLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stock Control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(102, 204, 0))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Current Quantity:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Add Quantity:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Product Name:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Last Updated:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLastUpdated, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtProductName)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCurrentQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtAddQuantity))))
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCurrentQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAddQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stock Status Monitor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Stock Condition: ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Low Stock Alert / Notes:");

        cmbStockCondition.setForeground(new java.awt.Color(51, 204, 0));
        cmbStockCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Good", "Damaged", "Expired" }));

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setRows(5);
        jTextArea1.setText("stock is witin safe range.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(cmbStockCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbStockCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddStock.setBackground(new java.awt.Color(76, 175, 80));
        btnAddStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddStock.setForeground(new java.awt.Color(242, 242, 242));
        btnAddStock.setText("Add Stock");
        btnAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStockActionPerformed(evt);
            }
        });

        btnUpdateStock.setBackground(new java.awt.Color(33, 150, 243));
        btnUpdateStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateStock.setForeground(new java.awt.Color(242, 242, 242));
        btnUpdateStock.setText("Update Stock");
        btnUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStockActionPerformed(evt);
            }
        });

        btnDetectLowStock.setBackground(new java.awt.Color(244, 67, 54));
        btnDetectLowStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDetectLowStock.setForeground(new java.awt.Color(242, 242, 242));
        btnDetectLowStock.setText("Detect Low Stock");
        btnDetectLowStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetectLowStockActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(158, 158, 158));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(242, 242, 242));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(96, 125, 139));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(242, 242, 242));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddStock)
                        .addGap(33, 33, 33)
                        .addComponent(btnUpdateStock)
                        .addGap(35, 35, 35)
                        .addComponent(btnDetectLowStock)
                        .addGap(30, 30, 30)
                        .addComponent(btnClear)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStock)
                    .addComponent(btnUpdateStock)
                    .addComponent(btnDetectLowStock)
                    .addComponent(btnClear)
                    .addComponent(btnBack))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStockActionPerformed
      try {

        // Required fields
        if (isEmpty(txtProductID) ||
            isEmpty(txtWarehouseLocation) ||
            isEmpty(txtAddQuantity)) {

            JOptionPane.showMessageDialog(this,
                    "Please fill Product ID, Warehouse Location and Quantity first.",
                    "Missing Data",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int productID =
                Integer.parseInt(txtProductID.getText().trim());

        String location =
                txtWarehouseLocation.getText().trim();

        int addQty =
                Integer.parseInt(txtAddQuantity.getText().trim());

        if (addQty <= 0) {

            JOptionPane.showMessageDialog(this,
                    "Quantity must be greater than zero.");
            return;
        }

        try (Connection con = DBConnection.connect()) {

            // Search by Product ID (not inventory_id)
            String checkSql =
            "SELECT quantity FROM inventory WHERE product_id=?";

            PreparedStatement check =
                    con.prepareStatement(checkSql);

            check.setInt(1, productID);

            ResultSet rs = check.executeQuery();

            if (rs.next()) {

                // Product exists -> add quantity
                String updateSql =
                "UPDATE inventory SET quantity = quantity + ?, "
              + "warehouse_location=?, "
              + "last_updated=NOW() "
              + "WHERE product_id=?";

                PreparedStatement ps =
                        con.prepareStatement(updateSql);

                ps.setInt(1, addQty);
                ps.setString(2, location);
                ps.setInt(3, productID);

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,
                        "Stock added successfully.");

            } else {

                // New product in inventory
                String insertSql =
                "INSERT INTO inventory(product_id,warehouse_location,quantity,availability,stock_condition,last_updated) "
              + "VALUES(?,?,?,?,?,NOW())";

                PreparedStatement ps =
                        con.prepareStatement(insertSql);

                ps.setInt(1, productID);
                ps.setString(2, location);
                ps.setInt(3, addQty);
                ps.setString(4, "Available");
                ps.setString(5, "In Stock");

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,
                        "New inventory record added.");
            }

            loadInventoryByProductID(productID);
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Product ID and Quantity must be numbers.");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAddStockActionPerformed

    private void btnUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStockActionPerformed
      
       try {

        // Check required fields
        if (isEmpty(txtProductID) || isEmpty(txtCurrentQuantity)) {
            JOptionPane.showMessageDialog(this,
                    "Please enter Product ID and Current Quantity first.");
            return;
        }

        int productId = Integer.parseInt(
                txtProductID.getText().trim());

        int newQty = Integer.parseInt(
                txtCurrentQuantity.getText().trim());

        if (newQty < 0) {
            JOptionPane.showMessageDialog(this,
                    "Quantity cannot be negative.");
            return;
        }

        try (Connection con = DBConnection.connect()) {

            // check if product exists in inventory
            String checkSql =
                    "SELECT * FROM inventory WHERE product_id=?";
            PreparedStatement check =
                    con.prepareStatement(checkSql);

            check.setInt(1, productId);

            ResultSet rs = check.executeQuery();

            if (rs.next()) {

                String updateSql =
                "UPDATE inventory SET quantity=?, last_updated=NOW() WHERE product_id=?";

                PreparedStatement ps =
                        con.prepareStatement(updateSql);

                ps.setInt(1, newQty);
                ps.setInt(2, productId);

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,
                        "Stock updated successfully.");

                loadInventoryByProductID(productId);

            } else {

                JOptionPane.showMessageDialog(this,
                        "This Product ID does not exist in inventory.");

            }
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Product ID and Quantity must be numbers.");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnUpdateStockActionPerformed

    private void btnDetectLowStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetectLowStockActionPerformed
  
       try {

        if (isEmpty(txtProductID) ||
            isEmpty(txtWarehouseLocation)) {

            JOptionPane.showMessageDialog(this,
                    "Please enter Product ID and Warehouse Location first.");
            return;
        }

        int productId =
                Integer.parseInt(
                txtProductID.getText().trim());

        String location =
                txtWarehouseLocation.getText().trim();

        try (Connection con = DBConnection.connect()) {

            String sql =
            "SELECT quantity, stock_condition " +
            "FROM inventory " +
            "WHERE product_id=? AND warehouse_location=?";

            PreparedStatement ps =
                    con.prepareStatement(sql);

            ps.setInt(1, productId);
            ps.setString(2, location);

            ResultSet rs =
                    ps.executeQuery();

            if (rs.next()) {

                int qty =
                        rs.getInt("quantity");

                String condition =
                        rs.getString(
                        "stock_condition");

                txtCurrentQuantity.setText(
                        String.valueOf(qty));

                cmbStockCondition.setSelectedItem(
                        condition);

                int min = 5;

                if (condition.equalsIgnoreCase(
                        "Damaged")) {

                    jTextArea1.setText(
                            "Product is damaged.");

                    JOptionPane.showMessageDialog(
                            this,
                            "Damaged product.");

                } else if (condition.equalsIgnoreCase(
                        "Expired")) {

                    jTextArea1.setText(
                            "Product is expired.");

                    JOptionPane.showMessageDialog(
                            this,
                            "Expired product.");

                } else if (qty <= min) {

                    jTextArea1.setText(
                            "Low stock detected.");

                    JOptionPane.showMessageDialog(
                            this,
                            "Low stock.");

                } else {

                    jTextArea1.setText(
                            "Stock is within safe range.");

                    JOptionPane.showMessageDialog(
                            this,
                            "Stock level is safe.");
                }

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "No matching product found in this warehouse.");
            }

        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Product ID must be a number.");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());
    }
    }//GEN-LAST:event_btnDetectLowStockActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
  
    txtProductID.setText("");
    txtWarehouseLocation.setText("");
    txtCurrentQuantity.setText("");
    txtAddQuantity.setText("");
    txtProductName.setText("");
    txtLastUpdated.setText("");

    cmbStockCondition.setSelectedIndex(0);

    jTextArea1.setText("");

    JOptionPane.showMessageDialog(this,
            "Fields cleared.");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      new LoginGuii().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private int readRequiredInt(javax.swing.JTextField field, String fieldName) {
        Integer value = readOptionalInt(field, fieldName);
        if (value == null) {
            throw new IllegalArgumentException(fieldName + " must be provided.");
        }
        return value;
    }

    private Integer readOptionalInt(javax.swing.JTextField field, String fieldName) {
        String value = normalizeInput(field);
        if (value == null) {
            return null;
        }

        try {
            return Integer.parseInt(value);
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException(fieldName + " must be a valid number.");
        }
    }

    private String readRequiredText(javax.swing.JTextField field, String fieldName) {
        String value = normalizeInput(field);
        if (value == null) {
            throw new IllegalArgumentException(fieldName + " cannot be empty.");
        }
        return value;
    }

    private String normalizeInput(javax.swing.JTextField field) {
        String value = field.getText() == null ? "" : field.getText().trim();
        if (value.isBlank() || value.startsWith("jTextField") || value.startsWith("TextField")) {
            return null;
        }
        return value;
    }

   
private void applyInventoryToForm(Inventory inventory) {

    if (inventory == null) {
        return;
    }

    // removed txtInventoryID

    txtProductID.setText(
            String.valueOf(inventory.getProductID()));

    txtProductName.setText(
            safeText(inventory.getProductName()));

    txtWarehouseLocation.setText(
            safeText(inventory.getWarehouseLocation()));

    txtCurrentQuantity.setText(
            String.valueOf(inventory.getStockLevel()));

    txtAddQuantity.setText("");

    txtProductName.setText(
            String.valueOf(inventory.getReorderThreshold()));

    txtLastUpdated.setText(
            safeText(inventory.getLastUpdated()));

    jTextArea1.setText(
            safeText(inventory.getLowStockNotes()));

    // removed cmbAvailability
    setComboValue(cmbStockCondition,
            inventory.getStockCondition());
}
    private void prefillFromProduct() {

    if (productContext == null) {
        return;
    }

    txtProductID.setText(
            String.valueOf(productContext.getProductID()));

    txtProductName.setText(
            safeText(productContext.getProductName()));

    Inventory inventory =
            productContext.getInventory();

    if (inventory != null) {

        // removed txtInventoryID

        txtWarehouseLocation.setText(
                safeText(inventory.getWarehouseLocation()));

        txtCurrentQuantity.setText(
                String.valueOf(inventory.getStockLevel()));

        txtProductName.setText(
                String.valueOf(inventory.getReorderThreshold()));

        txtLastUpdated.setText(
                safeText(inventory.getLastUpdated()));

        jTextArea1.setText(
                safeText(inventory.getLowStockNotes()));

        // removed cmbAvailability
        setComboValue(cmbStockCondition,
                inventory.getStockCondition());
    }
}

    private void setComboValue(javax.swing.JComboBox<String> comboBox, String value) {
        if (value == null || value.isBlank()) {
            return;
        }

        for (int i = 0; i < comboBox.getItemCount(); i++) {
            if (value.equalsIgnoreCase(comboBox.getItemAt(i))) {
                comboBox.setSelectedIndex(i);
                return;
            }
        }
    }

    private String safeText(String value) {
        return value == null ? "" : value;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStock;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDetectLowStock;
    private javax.swing.JButton btnUpdateStock;
    private javax.swing.JComboBox<String> cmbStockCondition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtAddQuantity;
    private javax.swing.JTextField txtCurrentQuantity;
    private javax.swing.JTextField txtLastUpdated;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtWarehouseLocation;
    // End of variables declaration//GEN-END:variables
}

