/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplychaintrackingsystem;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author M-ABEER
 */
public class LogisticsGUI extends javax.swing.JFrame {
    
    
    private LogisticsController logisticsController;
    private Logistics currentLogistics;
    private final List<String> logisticsRecords = new ArrayList<>();
    /**
     * Creates new form LogisticsGUI
     */
    public LogisticsGUI() {
    try {
        this.logisticsController = new LogisticsController();
        this.currentLogistics = logisticsController.getLogistics();
    } catch (Exception ex) {
        this.logisticsController = null;
        this.currentLogistics = null;
    }

       initComponents();
       configureDefaults();
       populateProfile();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecordDelivery = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        DeliveryDate = new javax.swing.JTextField();
        ReceverName = new javax.swing.JTextField();
        DeliveryLocation = new javax.swing.JTextField();
        DeliveryIssue = new javax.swing.JTextField();
        ShipmentId = new javax.swing.JTextField();
        DeliveryStatus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        CurrentLocation = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        logisticsID = new javax.swing.JTextField();
        Department = new javax.swing.JTextField();
        AssignedRegion = new javax.swing.JTextField();
        contactNumber = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ScheduleDelivery = new javax.swing.JButton();
        ReportIssue = new javax.swing.JButton();
        MonitorConditions = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RecordDelivery.setBackground(new java.awt.Color(76, 175, 80));
        RecordDelivery.setForeground(new java.awt.Color(242, 242, 242));
        RecordDelivery.setText("Record Delivery ");
        RecordDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordDeliveryActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(96, 125, 139));
        btnBack.setForeground(new java.awt.Color(242, 242, 242));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("Shipment Operations");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Shipment ID:");

        jLabel17.setText("Delivery Date");

        jLabel18.setText("Receiver Name:");

        jLabel19.setText("Delivery Location:");

        jLabel20.setText("Delivery Status:");

        jLabel21.setText("Delivery Issue:");

        DeliveryLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryLocationActionPerformed(evt);
            }
        });

        ShipmentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShipmentIdActionPerformed(evt);
            }
        });

        DeliveryStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "In Transit", "Out for Delivery", "Delivered", "Delayed", "Cancelled" }));
        DeliveryStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryStatusActionPerformed(evt);
            }
        });

        jLabel3.setText("current location:");

        CurrentLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(114, 114, 114))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ReceverName, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(DeliveryDate)
                                    .addComponent(ShipmentId)
                                    .addComponent(DeliveryLocation)))
                            .addComponent(jLabel17)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DeliveryStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DeliveryIssue)
                                    .addComponent(CurrentLocation)))
                            .addComponent(jLabel12))
                        .addContainerGap(173, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ShipmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(DeliveryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ReceverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(DeliveryLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(DeliveryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(DeliveryIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 204));
        jLabel11.setText("Logistics Profile");

        jLabel13.setText("Logistics ID:");

        jLabel14.setText("Department:");

        jLabel15.setText("Assigned Region");

        jLabel16.setText("Contact Number:");

        logisticsID.setEditable(false);

        Department.setEditable(false);
        Department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentActionPerformed(evt);
            }
        });

        AssignedRegion.setEditable(false);
        AssignedRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignedRegionActionPerformed(evt);
            }
        });

        contactNumber.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AssignedRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logisticsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(logisticsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(AssignedRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Logistics Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ScheduleDelivery.setBackground(new java.awt.Color(33, 150, 243));
        ScheduleDelivery.setForeground(new java.awt.Color(242, 242, 242));
        ScheduleDelivery.setText("Schedule Delivery");
        ScheduleDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleDeliveryActionPerformed(evt);
            }
        });

        ReportIssue.setBackground(new java.awt.Color(255, 152, 0));
        ReportIssue.setForeground(new java.awt.Color(242, 242, 242));
        ReportIssue.setText("Report Issue");
        ReportIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportIssueActionPerformed(evt);
            }
        });

        MonitorConditions.setBackground(new java.awt.Color(156, 39, 176));
        MonitorConditions.setForeground(new java.awt.Color(242, 242, 242));
        MonitorConditions.setText("Monitor Conditions");
        MonitorConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonitorConditionsActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(158, 158, 158));
        btnClear.setForeground(new java.awt.Color(242, 242, 242));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScheduleDelivery, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ReportIssue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnClear)
                        .addGap(71, 71, 71)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(MonitorConditions)
                        .addGap(37, 37, 37)
                        .addComponent(RecordDelivery)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MonitorConditions)
                    .addComponent(ScheduleDelivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RecordDelivery))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(ReportIssue)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new LoginGuii(AppContext.authBoundary()).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void DeliveryLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeliveryLocationActionPerformed

    private void ShipmentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShipmentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShipmentIdActionPerformed

    private void DeliveryStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeliveryStatusActionPerformed

    private void CurrentLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentLocationActionPerformed

    private void DepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartmentActionPerformed

    private void AssignedRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignedRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignedRegionActionPerformed

    private void ScheduleDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleDeliveryActionPerformed
       try {
        int shipmentID = parseRequiredInt(ShipmentId.getText(), "Shipment ID");
        Date deliveryDate = parseRequiredDate(DeliveryDate.getText(), "Delivery Date");
        String deliveryLocation = readRequiredText(DeliveryLocation.getText(), "Delivery Location");

        try {
            if (logisticsController != null) {
                logisticsController.scheduleDelivery(shipmentID, deliveryDate);
            } else {
                Shipment shipment = createLocalShipmentIfNeeded(shipmentID);
                shipment.setDeliveryLocation(deliveryLocation);
                currentLogistics.scheduleDelivery(shipmentID, deliveryDate);
            }
        } catch (Exception ex) {
            Shipment shipment = createLocalShipmentIfNeeded(shipmentID);
            shipment.setDeliveryLocation(deliveryLocation);
            currentLogistics.scheduleDelivery(shipmentID, deliveryDate);
        }

        String record =
                "Delivery Scheduled\n"
                + "Shipment ID: " + shipmentID + "\n"
                + "Delivery Date: " + DeliveryDate.getText().trim() + "\n"
                + "Delivery Location: " + deliveryLocation + "\n"
                + "Status: Scheduled";

        logisticsRecords.add(record);
        DeliveryStatus.setSelectedItem("In Transit");

        JOptionPane.showMessageDialog(this,
                record,
                "Schedule Delivery",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while scheduling delivery: " + ex.getMessage(),
                "Logistics Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_ScheduleDeliveryActionPerformed

    private void MonitorConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonitorConditionsActionPerformed
      try {
        int shipmentID = parseRequiredInt(ShipmentId.getText(), "Shipment ID");
        String currentLocation = readRequiredText(CurrentLocation.getText(), "Current Location");

        Shipment shipment;

        try {
            if (logisticsController != null) {
                logisticsController.monitorTransportConditions(shipmentID);
            }

            shipment = findLocalShipment(shipmentID);

            if (shipment == null) {
                shipment = createLocalShipmentIfNeeded(shipmentID);
            }

        } catch (Exception ex) {
            shipment = createLocalShipmentIfNeeded(shipmentID);
        }

        shipment.updateLocation(currentLocation);

        if (shipment.getLatestSensorData() == null) {
            shipment.updateConditions(5.0, 50.0);
        }

        SensorData sensorData = shipment.getLatestSensorData();

        String conditionResult =
                "Transport Conditions\n"
                + "Shipment ID: " + shipmentID + "\n"
                + "Current Location: " + shipment.getCurrentLocation() + "\n"
                + "Temperature: " + sensorData.getTemperature() + "\n"
                + "Humidity: " + sensorData.getHumidity() + "\n"
                + "Recorded Time: " + sensorData.getRecordedTime() + "\n"
                + "Status: Conditions monitored";

        logisticsRecords.add(conditionResult);

        JOptionPane.showMessageDialog(this,
                conditionResult,
                "Monitor Conditions",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while monitoring conditions: " + ex.getMessage(),
                "Logistics Error",
                JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_MonitorConditionsActionPerformed

    private void RecordDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordDeliveryActionPerformed
         try {
        int shipmentID = parseRequiredInt(ShipmentId.getText(), "Shipment ID");
        String receiverName = readRequiredText(ReceverName.getText(), "Receiver Name");
        String deliveryLocation = readRequiredText(DeliveryLocation.getText(), "Delivery Location");
        String deliveryStatus = (String) DeliveryStatus.getSelectedItem();

        try {
            if (logisticsController != null) {
                logisticsController.recordDeliveryDetails(
                        shipmentID,
                        receiverName,
                        deliveryLocation,
                        deliveryStatus
                );
            } else {
                createLocalShipmentIfNeeded(shipmentID);
                currentLogistics.recordDeliveryDetails(
                        shipmentID,
                        receiverName,
                        deliveryLocation,
                        deliveryStatus
                );
            }
        } catch (Exception ex) {
            createLocalShipmentIfNeeded(shipmentID);
            currentLogistics.recordDeliveryDetails(
                    shipmentID,
                    receiverName,
                    deliveryLocation,
                    deliveryStatus
            );
        }

        String record =
                "Delivery Recorded\n"
                + "Shipment ID: " + shipmentID + "\n"
                + "Receiver Name: " + receiverName + "\n"
                + "Delivery Location: " + deliveryLocation + "\n"
                + "Delivery Status: "+ deliveryStatus ;

        logisticsRecords.add(record);
        

        JOptionPane.showMessageDialog(this,
                record,
                "Record Delivery",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while recording delivery: " + ex.getMessage(),
                "Logistics Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_RecordDeliveryActionPerformed

    private void ReportIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportIssueActionPerformed
       try {
        int shipmentID = parseRequiredInt(ShipmentId.getText(), "Shipment ID");
        String issue = readRequiredText(DeliveryIssue.getText(), "Delivery Issue");

        try {
            if (logisticsController != null) {
                logisticsController.reportDeliveryIssue(shipmentID, issue);
            } else {
                createLocalShipmentIfNeeded(shipmentID);
                currentLogistics.reportDeliveryIssue(shipmentID, issue);
            }
        } catch (Exception ex) {
            createLocalShipmentIfNeeded(shipmentID);
            currentLogistics.reportDeliveryIssue(shipmentID, issue);
        }

        String issueRecord =
                "Delivery Issue Reported\n"
                + "Shipment ID: " + shipmentID + "\n"
                + "Issue: " + issue + "\n"
                + "Status: Issue Reported";

        logisticsRecords.add(issueRecord);
        DeliveryStatus.setSelectedItem("Delayed");

        JOptionPane.showMessageDialog(this,
                issueRecord,
                "Report Issue",
                JOptionPane.WARNING_MESSAGE);

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while reporting issue: " + ex.getMessage(),
                "Logistics Error",
                JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_ReportIssueActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
         ShipmentId.setText("");
    DeliveryDate.setText("");
    ReceverName.setText("");
    DeliveryLocation.setText("");
    CurrentLocation.setText("");
    DeliveryIssue.setText("");
    DeliveryStatus.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    
    private void configureDefaults() {
    logisticsID.setText("");
    Department.setText("");
    AssignedRegion.setText("");
    contactNumber.setText("");

    ShipmentId.setText("");
    DeliveryDate.setText("");
    ReceverName.setText("");
    DeliveryLocation.setText("");
    CurrentLocation.setText("");
    DeliveryIssue.setText("");
    DeliveryStatus.setSelectedIndex(0);
}

private void populateProfile() {
    if (currentLogistics == null) {
        currentLogistics = new Logistics(
                1,
                "Logistics User",
                "logistics@email.com",
                "password123",
                "Logistics",
                1,
                "Logistics Department",
                "Cairo",
                "01000000000"
        );
    }

    logisticsID.setText(String.valueOf(currentLogistics.getLogisticsID()));
    Department.setText(currentLogistics.getDepartment());
    AssignedRegion.setText(currentLogistics.getAssignedRegion());
    contactNumber.setText(currentLogistics.getContactNumber());
}

private Shipment createLocalShipmentIfNeeded(int shipmentID) {
    Shipment existingShipment = findLocalShipment(shipmentID);

    if (existingShipment != null) {
        return existingShipment;
    }

    Shipment shipment = new Shipment(shipmentID);
    shipment.setOrigin("Warehouse");
    shipment.setDestination("Delivery Location");
    shipment.setCurrentLocation("Warehouse");
    shipment.setWeight(1.0);
    shipment.setDistance(1.0);

    currentLogistics.addShipment(shipment);
    return shipment;
}

private Shipment findLocalShipment(int shipmentID) {
    if (currentLogistics == null) {
        return null;
    }

    for (Shipment shipment : currentLogistics.getShipments()) {
        if (shipment.getShipmentID() == shipmentID) {
            return shipment;
        }
    }

    return null;
}

private int parseRequiredInt(String value, String fieldName) {
    String text = value == null ? "" : value.trim();

    if (text.isBlank()) {
        throw new IllegalArgumentException(fieldName + " cannot be empty.");
    }

    if (!text.matches("\\d+")) {
        throw new IllegalArgumentException(fieldName + " must contain numbers only.");
    }

    int number = Integer.parseInt(text);

    if (number <= 0) {
        throw new IllegalArgumentException(fieldName + " must be greater than 0.");
    }

    return number;
}

private String readRequiredText(String value, String fieldName) {
    String text = value == null ? "" : value.trim();

    if (text.isBlank()) {
        throw new IllegalArgumentException(fieldName + " cannot be empty.");
    }

    return text;
}

private Date parseRequiredDate(String value, String fieldName) {
    String text = readRequiredText(value, fieldName);

    try {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        formatter.setLenient(false);
        return formatter.parse(text);
    } catch (ParseException ex) {
        throw new IllegalArgumentException(fieldName + " must be in format yyyy-MM-dd.");
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogisticsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogisticsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogisticsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogisticsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogisticsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AssignedRegion;
    private javax.swing.JTextField CurrentLocation;
    private javax.swing.JTextField DeliveryDate;
    private javax.swing.JTextField DeliveryIssue;
    private javax.swing.JTextField DeliveryLocation;
    private javax.swing.JComboBox<String> DeliveryStatus;
    private javax.swing.JTextField Department;
    private javax.swing.JButton MonitorConditions;
    private javax.swing.JTextField ReceverName;
    private javax.swing.JButton RecordDelivery;
    private javax.swing.JButton ReportIssue;
    private javax.swing.JButton ScheduleDelivery;
    private javax.swing.JTextField ShipmentId;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JTextField contactNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField logisticsID;
    // End of variables declaration//GEN-END:variables
}
