/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplychaintrackingsystem;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author M-ABEER
 */
public class product_GUI extends javax.swing.JFrame {

private Manufacturer currentManufacturer;
private final List<Product> products = new ArrayList<>();
private final List<Inventory> inventoryRecords = new ArrayList<>();

    /**
     * Creates new form product_GUI
     */
       

     public product_GUI() {
    initComponents();
    configureDefaults();
    createDefaultManufacturer();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtRawMaterialSupplierID = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        btnAddProduct = new javax.swing.JButton();
        btnUpdateProduct = new javax.swing.JButton();
        btnCheckAvailability = new javax.swing.JButton();
        btnAddtoInventory = new javax.swing.JButton();
        btnReportIssue = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProductNotes = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtExpiryDate = new javax.swing.JTextField();
        cmbQualityStatus = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        ManufactureDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 204, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Product ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Product Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Category:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Raw Material Supplier ID:");

        txtProductID.setEditable(false);

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Beverage", "Medicine", "Electronics", "Raw Material", "Other" }));
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProductID, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(txtProductName))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRawMaterialSupplierID)
                    .addComponent(cmbCategory, 0, 113, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtRawMaterialSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnAddProduct.setBackground(new java.awt.Color(33, 150, 243));
        btnAddProduct.setForeground(new java.awt.Color(242, 242, 242));
        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnUpdateProduct.setBackground(new java.awt.Color(156, 39, 176));
        btnUpdateProduct.setForeground(new java.awt.Color(242, 242, 242));
        btnUpdateProduct.setText("Update Product");
        btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductActionPerformed(evt);
            }
        });

        btnCheckAvailability.setBackground(new java.awt.Color(255, 152, 0));
        btnCheckAvailability.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckAvailability.setText("Check Availability");
        btnCheckAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAvailabilityActionPerformed(evt);
            }
        });

        btnAddtoInventory.setBackground(new java.awt.Color(76, 175, 80));
        btnAddtoInventory.setForeground(new java.awt.Color(242, 242, 242));
        btnAddtoInventory.setText("Add to Inventory");
        btnAddtoInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoInventoryActionPerformed(evt);
            }
        });

        btnReportIssue.setBackground(new java.awt.Color(244, 67, 54));
        btnReportIssue.setForeground(new java.awt.Color(242, 242, 242));
        btnReportIssue.setText("Report Issue");
        btnReportIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportIssueActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(158, 158, 158));
        btnClear.setForeground(new java.awt.Color(242, 242, 242));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(96, 125, 139));
        btnBack.setForeground(new java.awt.Color(242, 242, 242));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 204, 0))); // NOI18N

        txtProductNotes.setColumns(20);
        txtProductNotes.setForeground(new java.awt.Color(102, 102, 102));
        txtProductNotes.setRows(5);
        txtProductNotes.setText("Enter notes, issues or important information about the product..");
        jScrollPane1.setViewportView(txtProductNotes);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setText("Product Notes / Issue Report:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Product Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Stock Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Price:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Quantity:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Expiry Date:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Quality Status:");

        cmbQualityStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approved", "Pending Inspection", "Rejected", "Expired" }));

        jLabel11.setText("Manufacture Date");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(txtPrice))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbQualityStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpiryDate)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(ManufactureDate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cmbQualityStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ManufactureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCheckAvailability)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddtoInventory))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnReportIssue)
                        .addGap(27, 27, 27)
                        .addComponent(btnClear)
                        .addGap(27, 27, 27)
                        .addComponent(btnBack)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct)
                    .addComponent(btnUpdateProduct)
                    .addComponent(btnCheckAvailability)
                    .addComponent(btnAddtoInventory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReportIssue)
                    .addComponent(btnClear)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
try {
        String productName = readRequiredText(txtProductName.getText(), "Product Name");
        String category = (String) cmbCategory.getSelectedItem();
        int supplierID = parseRequiredInt(txtRawMaterialSupplierID.getText(), "Raw Material Supplier ID");
        double price = parseRequiredDouble(txtPrice.getText(), "Price");
        int quantity = parseRequiredInt(txtQuantity.getText(), "Quantity");
        Date manufactureDate = parseRequiredDate(ManufactureDate.getText(), "Manufacture Date");
        Date expiryDate = parseRequiredDate(txtExpiryDate.getText(), "Expiry Date");
        String qualityStatus = (String) cmbQualityStatus.getSelectedItem();
        String notes = getNotesText();

        if (!expiryDate.after(manufactureDate)) {
            throw new IllegalArgumentException("Expiry Date must be after Manufacture Date.");
        }

        Product product = new Product();
        product.setProductName(productName);
        product.setCategory(category);
        product.setUnitPrice(price);
        product.setManufactureDate(manufactureDate);
        product.setExpiryDate(expiryDate);
        product.setStatus(qualityStatus);
        product.setIssueReport(notes);

        products.add(product);

        if (currentManufacturer != null) {
            currentManufacturer.startProduction(product);
            currentManufacturer.completeProduction(product, quantity);
        }

        txtProductID.setText(String.valueOf(product.getProductID()));

        String message =
                "Product Added Successfully\n"
                + "Product ID: " + product.getProductID() + "\n"
                + "Product Name: " + product.getProductName() + "\n"
                + "Category: " + product.getCategory() + "\n"
                + "Raw Material Supplier ID: " + supplierID + "\n"
                + "Price: " + product.getUnitPrice() + "\n"
                + "Quantity: " + quantity + "\n"
                + "Quality Status: " + product.getStatus();

        JOptionPane.showMessageDialog(this,
                message,
                "Add Product",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while adding product: " + ex.getMessage(),
                "Product Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
try {
        int productID = parseRequiredInt(txtProductID.getText(), "Product ID");

        Product product = findProductByID(productID);

        if (product == null) {
            throw new IllegalArgumentException("Product ID was not found.");
        }

        String productName = readRequiredText(txtProductName.getText(), "Product Name");
        String category = (String) cmbCategory.getSelectedItem();
        double price = parseRequiredDouble(txtPrice.getText(), "Price");
        Date manufactureDate = parseRequiredDate(ManufactureDate.getText(), "Manufacture Date");
        Date expiryDate = parseRequiredDate(txtExpiryDate.getText(), "Expiry Date");
        String qualityStatus = (String) cmbQualityStatus.getSelectedItem();
        String notes = getNotesText();

        if (!expiryDate.after(manufactureDate)) {
            throw new IllegalArgumentException("Expiry Date must be after Manufacture Date.");
        }

        product.setProductName(productName);
        product.setCategory(category);
        product.setUnitPrice(price);
        product.setManufactureDate(manufactureDate);
        product.setExpiryDate(expiryDate);
        product.setStatus(qualityStatus);
        product.setIssueReport(notes);

        String message =
                "Product Updated Successfully\n"
                + "Product ID: " + product.getProductID() + "\n"
                + "Product Name: " + product.getProductName() + "\n"
                + "Category: " + product.getCategory() + "\n"
                + "Price: " + product.getUnitPrice() + "\n"
                + "Quality Status: " + product.getStatus();

        JOptionPane.showMessageDialog(this,
                message,
                "Update Product",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while updating product: " + ex.getMessage(),
                "Product Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnUpdateProductActionPerformed

    private void btnCheckAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAvailabilityActionPerformed
 try {
        int productID = parseRequiredInt(txtProductID.getText(), "Product ID");

        Product product = findProductByID(productID);

        if (product == null) {
            throw new IllegalArgumentException("Product ID was not found.");
        }

        boolean available = product.isAvailable();

        Inventory inventory = findInventoryByProductID(productID);

        String inventoryInfo;

        if (inventory == null) {
            inventoryInfo = "Inventory Record: Not added to inventory yet.";
        } else {
            inventoryInfo =
                    "Stock Level: " + inventory.getStockLevel() + "\n"
                    + "Availability: " + inventory.getAvailability() + "\n"
                    + "Stock Condition: " + inventory.getStockCondition();
        }

        String message =
                "Product Availability Check\n"
                + "Product ID: " + product.getProductID() + "\n"
                + "Product Name: " + product.getProductName() + "\n"
                + "Product Status: " + product.getStatus() + "\n"
                + "Available: " + available + "\n"
                + inventoryInfo;

        JOptionPane.showMessageDialog(this,
                message,
                "Check Availability",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while checking availability: " + ex.getMessage(),
                "Product Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnCheckAvailabilityActionPerformed

    private void btnAddtoInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoInventoryActionPerformed
 try {
        int productID = parseRequiredInt(txtProductID.getText(), "Product ID");
        int quantity = parseRequiredInt(txtQuantity.getText(), "Quantity");

        Product product = findProductByID(productID);

        if (product == null) {
            throw new IllegalArgumentException("Product must be added before adding it to inventory.");
        }

        String qualityStatus = product.getStatus();

        if (!"Approved".equalsIgnoreCase(qualityStatus)) {
            throw new IllegalStateException("Only approved products can be added to inventory.");
        }

        Inventory inventory = findInventoryByProductID(productID);

        if (inventory == null) {
            inventory = new Inventory();
            inventory.setProductID(product.getProductID());
            inventory.setProductName(product.getProductName());
            inventory.setProduct(product);
            inventory.setWarehouseLocation("Manufacturer Warehouse");
            inventory.setStockLevel(quantity);
            product.setInventory(inventory);
            inventoryRecords.add(inventory);
        } else {
            inventory.addStock(quantity);
        }

        String message =
                "Product Added to Inventory\n"
                + "Product ID: " + product.getProductID() + "\n"
                + "Product Name: " + product.getProductName() + "\n"
                + "Quantity Added: " + quantity + "\n"
                + "Current Stock Level: " + inventory.getStockLevel() + "\n"
                + "Availability: " + inventory.getAvailability() + "\n"
                + "Stock Condition: " + inventory.getStockCondition();

        JOptionPane.showMessageDialog(this,
                message,
                "Add to Inventory",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException | IllegalStateException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while adding to inventory: " + ex.getMessage(),
                "Inventory Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAddtoInventoryActionPerformed

    private void btnReportIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportIssueActionPerformed
 try {
        int productID = parseRequiredInt(txtProductID.getText(), "Product ID");
        String issue = readRequiredText(txtProductNotes.getText(), "Product Notes / Issue Report");

        if (isDefaultNotes(issue)) {
            throw new IllegalArgumentException("Please enter a real issue report.");
        }

        Product product = findProductByID(productID);

        if (product == null) {
            throw new IllegalArgumentException("Product ID was not found.");
        }

        product.setIssueReport(issue);
        product.setStatus("Rejected");

        cmbQualityStatus.setSelectedItem("Rejected");

        String message =
                "Product Issue Reported\n"
                + "Product ID: " + product.getProductID() + "\n"
                + "Product Name: " + product.getProductName() + "\n"
                + "Issue: " + issue + "\n"
                + "New Quality Status: Rejected";

        JOptionPane.showMessageDialog(this,
                message,
                "Report Issue",
                JOptionPane.WARNING_MESSAGE);

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while reporting issue: " + ex.getMessage(),
                "Product Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnReportIssueActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
 clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
try {
        new ManufactureGuiii().setVisible(true);
        dispose();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unable to return to manufacturer page: " + ex.getMessage(),
                "Navigation Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnBackActionPerformed
private void configureDefaults() {
    txtProductID.setText("");
    txtProductName.setText("");
    txtRawMaterialSupplierID.setText("");
    txtPrice.setText("");
    txtQuantity.setText("");
    txtExpiryDate.setText("");
    ManufactureDate.setText("");
    cmbCategory.setSelectedIndex(0);
    cmbQualityStatus.setSelectedIndex(0);
    txtProductNotes.setText("Enter notes, issues or important information about the product..");
}

private void createDefaultManufacturer() {
    currentManufacturer = new Manufacturer(
            1,
            "Manufacturer User",
            "manufacturer@email.com",
            "password123",
            "Manufacturer",
            "Cairo Factory"
    );
}

private void clearFields() {
    txtProductID.setText("");
    txtProductName.setText("");
    txtRawMaterialSupplierID.setText("");
    txtPrice.setText("");
    txtQuantity.setText("");
    txtExpiryDate.setText("");
    ManufactureDate.setText("");
    cmbCategory.setSelectedIndex(0);
    cmbQualityStatus.setSelectedIndex(0);
    txtProductNotes.setText("Enter notes, issues or important information about the product..");
}

private Product findProductByID(int productID) {
    for (Product product : products) {
        if (product.getProductID() == productID) {
            return product;
        }
    }
    return null;
}

private Inventory findInventoryByProductID(int productID) {
    for (Inventory inventory : inventoryRecords) {
        if (inventory.getProductID() == productID) {
            return inventory;
        }
    }
    return null;
}

private int parseRequiredInt(String value, String fieldName) {
    String text = value == null ? "" : value.trim();

    if (text.isBlank()) {
        throw new IllegalArgumentException(fieldName + " cannot be empty.");
    }

    if (!text.matches("\\d+")) {
        throw new IllegalArgumentException(fieldName + " must contain numbers only.");
    }

    int number = Integer.parseInt(text);

    if (number <= 0) {
        throw new IllegalArgumentException(fieldName + " must be greater than 0.");
    }

    return number;
}

private double parseRequiredDouble(String value, String fieldName) {
    String text = value == null ? "" : value.trim();

    if (text.isBlank()) {
        throw new IllegalArgumentException(fieldName + " cannot be empty.");
    }

    try {
        double number = Double.parseDouble(text);

        if (number <= 0) {
            throw new IllegalArgumentException(fieldName + " must be greater than 0.");
        }

        return number;

    } catch (NumberFormatException ex) {
        throw new IllegalArgumentException(fieldName + " must be a valid number.");
    }
}

private String readRequiredText(String value, String fieldName) {
    String text = value == null ? "" : value.trim();

    if (text.isBlank()) {
        throw new IllegalArgumentException(fieldName + " cannot be empty.");
    }

    return text;
}

private Date parseRequiredDate(String value, String fieldName) {
    String text = readRequiredText(value, fieldName);

    try {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        formatter.setLenient(false);
        return formatter.parse(text);
    } catch (ParseException ex) {
        throw new IllegalArgumentException(fieldName + " must be in format yyyy-MM-dd.");
    }
}

private String getNotesText() {
    String notes = txtProductNotes.getText();

    if (notes == null || isDefaultNotes(notes)) {
        return "";
    }

    return notes.trim();
}

private boolean isDefaultNotes(String text) {
    if (text == null) {
        return true;
    }

    return text.trim().equalsIgnoreCase("Enter notes, issues or important information about the product..");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ManufactureDate;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAddtoInventory;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckAvailability;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnReportIssue;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbQualityStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtExpiryDate;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextArea txtProductNotes;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtRawMaterialSupplierID;
    // End of variables declaration//GEN-END:variables
}
