/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplychaintrackingsystem;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;




/**
 *
 * @author M-ABEER
 */
public class Regulator_GUI extends javax.swing.JFrame {

    
    private UserController userController;
    private Regulator currentRegulator;
    private final List<String> auditRecords = new ArrayList<>();
    /**
     * Creates new form Regulator_GUI
     */
   public Regulator_GUI() {
    try {
        this.userController = AppContext.userController();
    } catch (Exception ex) {
        this.userController = null;
    }

    initComponents();
    configureDefaults();
    populateFromUserController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewTracking = new javax.swing.JButton();
        ReviewStorageConditions = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmbActivityType = new javax.swing.JComboBox<>();
        cmbRecordStatus = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReportSummary = new javax.swing.JTextArea();
        btnVerifyCompliance = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtProductID = new javax.swing.JTextField();
        txtTrackingRecordID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAuditNotes = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtShipmentID = new javax.swing.JTextField();
        btnGenerateReport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        RegulatorID = new javax.swing.JLabel();
        AgencyName = new javax.swing.JLabel();
        AccessLevel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRegulatorID = new javax.swing.JTextField();
        txtAgencyName = new javax.swing.JTextField();
        txtAuditRegion = new javax.swing.JTextField();
        txtAccessLevel = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnAuditActivity = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnViewTracking.setBackground(new java.awt.Color(0, 172, 193));
        btnViewTracking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewTracking.setForeground(new java.awt.Color(255, 255, 255));
        btnViewTracking.setText("View Tracking");
        btnViewTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTrackingActionPerformed(evt);
            }
        });

        ReviewStorageConditions.setBackground(new java.awt.Color(255, 152, 0));
        ReviewStorageConditions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ReviewStorageConditions.setForeground(new java.awt.Color(255, 255, 255));
        ReviewStorageConditions.setText("Review Storage Conditions");
        ReviewStorageConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewStorageConditionsActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tracking & Compliance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 204, 204))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 255, 204));

        cmbActivityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shipment Tracking", "Storage Conditions", "Inventory Status", "Product Traceability", "Compliance Violation", "Audit Review" }));

        cmbRecordStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Open", "Under Review", "Compliant", "Non-Compliant", "Resolved" }));
        cmbRecordStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRecordStatusActionPerformed(evt);
            }
        });

        jLabel11.setText("Activity Type");

        jLabel12.setText("Record Status");

        jLabel13.setText("Report Summary");

        txtReportSummary.setColumns(20);
        txtReportSummary.setRows(5);
        jScrollPane2.setViewportView(txtReportSummary);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbRecordStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbActivityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbActivityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRecordStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVerifyCompliance.setBackground(new java.awt.Color(76, 175, 80));
        btnVerifyCompliance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerifyCompliance.setForeground(new java.awt.Color(255, 255, 255));
        btnVerifyCompliance.setText("Verify Compliance");
        btnVerifyCompliance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyComplianceActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Audit Review", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 153, 51))); // NOI18N

        txtProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIDActionPerformed(evt);
            }
        });

        txtTrackingRecordID.setText(" ");
        txtTrackingRecordID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrackingRecordIDActionPerformed(evt);
            }
        });

        txtAuditNotes.setColumns(20);
        txtAuditNotes.setRows(5);
        jScrollPane1.setViewportView(txtAuditNotes);

        jLabel7.setText("Product ID");

        jLabel8.setText("Order ID");

        jLabel10.setText("Audit Notes");

        jLabel9.setText("Shipment ID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProductID, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(txtTrackingRecordID, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtShipmentID))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrackingRecordID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtShipmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        btnGenerateReport.setBackground(new java.awt.Color(106, 27, 154));
        btnGenerateReport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerateReport.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(96, 125, 139));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Regulator Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        RegulatorID.setText("Regulator ID");

        AgencyName.setText("Agency Name");

        AccessLevel.setText("Access Level: ");

        jLabel6.setText("Audit Region: ");

        txtRegulatorID.setEditable(false);

        txtAgencyName.setEditable(false);

        txtAccessLevel.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAuditRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegulatorID)
                            .addComponent(AgencyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAgencyName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegulatorID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegulatorID)
                    .addComponent(txtRegulatorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgencyName)
                    .addComponent(txtAgencyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccessLevel)
                    .addComponent(txtAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAuditRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnClear.setBackground(new java.awt.Color(158, 158, 158));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAuditActivity.setBackground(new java.awt.Color(21, 101, 192));
        btnAuditActivity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAuditActivity.setForeground(new java.awt.Color(255, 255, 255));
        btnAuditActivity.setText("Audit Activity ");
        btnAuditActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuditActivityActionPerformed(evt);
            }
        });

        jPanel7.setBackground(java.awt.SystemColor.activeCaption);
        jPanel7.setForeground(new java.awt.Color(0, 51, 204));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 204));
        jLabel15.setText("Regulator Management");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 204));
        jLabel16.setText("Audit, Compliance and Tracking Control");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAuditActivity)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnViewTracking))
                                .addComponent(btnGenerateReport))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(ReviewStorageConditions)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnVerifyCompliance))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnClear)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBack)
                                    .addGap(125, 125, 125))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30))))
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAuditActivity)
                    .addComponent(btnViewTracking)
                    .addComponent(ReviewStorageConditions)
                    .addComponent(btnVerifyCompliance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateReport)
                    .addComponent(btnClear)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTrackingActionPerformed
      try {
        Regulator regulator = ensureRegulator();

        int orderID = parseRequiredInt(txtTrackingRecordID.getText(), "Order ID");
        int shipmentID = parseRequiredInt(txtShipmentID.getText(), "Shipment ID");

        Order order = null;

        try {
            order = AppContext.orderController().getOrderByID(orderID);
        } catch (Exception ex) {
            order = null;
        }

        String trackingInfo;

        if (order != null) {
            regulator.viewTrackingRecords(order);
            trackingInfo = order.trackOrder();
        } else {
            trackingInfo =
                    "Tracking Record\n"
                    + "Order ID: " + orderID + "\n"
                    + "Shipment ID: " + shipmentID + "\n"
                    + "Status: Tracking record is under review.\n"
                    + "Activity Type: " + cmbActivityType.getSelectedItem();
        }

        txtAuditNotes.setText(trackingInfo);

        JOptionPane.showMessageDialog(this,
                trackingInfo,
                "Tracking Records",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while viewing tracking: " + ex.getMessage(),
                "Regulator Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnViewTrackingActionPerformed

    private void ReviewStorageConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewStorageConditionsActionPerformed
          try {
        Regulator regulator = ensureRegulator();

        int productID = parseRequiredInt(txtProductID.getText(), "Product ID");
        String productIDText = String.valueOf(productID);

        regulator.reviewStorageRecord(productIDText);

        Inventory inventory = new Inventory();
        inventory.setProductID(productID);
        inventory.setProductName("Product " + productID);
        inventory.setWarehouseLocation(regulator.getAuditRegion());
        inventory.setStockLevel(5);

        String storageReview =
                "Storage Conditions Review\n"
                + "Product ID: " + productIDText + "\n"
                + "Warehouse Region: " + regulator.getAuditRegion() + "\n"
                + "Stock Level: " + inventory.getStockLevel() + "\n"
                + "Availability: " + inventory.getAvailability() + "\n"
                + "Stock Condition: " + inventory.getStockCondition() + "\n"
                + "Low Stock Notes: " + inventory.getLowStockNotes();

        txtAuditNotes.setText(storageReview);
        txtReportSummary.setText(storageReview);
        auditRecords.add(storageReview);

        JOptionPane.showMessageDialog(this,
                "Storage conditions reviewed successfully.",
                "Storage Review",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this,
                "Product ID must be a valid number.",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while reviewing storage: " + ex.getMessage(),
                "Regulator Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_ReviewStorageConditionsActionPerformed

    private void cmbRecordStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRecordStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRecordStatusActionPerformed

    private void btnVerifyComplianceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyComplianceActionPerformed
        try {
        ensureRegulator();

        int productID = parseRequiredInt(txtProductID.getText(), "Product ID");
        int orderID = parseRequiredInt(txtTrackingRecordID.getText(), "Order ID");
        int shipmentID = parseRequiredInt(txtShipmentID.getText(), "Shipment ID");

        String activityType = (String) cmbActivityType.getSelectedItem();
        String recordStatus = (String) cmbRecordStatus.getSelectedItem();
        String notes = txtAuditNotes.getText() == null ? "" : txtAuditNotes.getText().trim();

        if (notes.isBlank()) {
            notes = "No audit notes provided.";
        }

        String complianceResult;

        if ("Non-Compliant".equalsIgnoreCase(recordStatus)) {
            complianceResult = "Compliance verification failed. The record is marked as Non-Compliant.";
        } else if ("Compliant".equalsIgnoreCase(recordStatus)) {
            complianceResult = "Compliance verification passed. The record is marked as Compliant.";
        } else {
            complianceResult = "Compliance verification is still under review.";
        }

        String summary =
                "Compliance Verification Summary\n"
                + "Product ID: " + productID + "\n"
                + "Order ID: " + orderID + "\n"
                + "Shipment ID: " + shipmentID + "\n"
                + "Activity Type: " + activityType + "\n"
                + "Record Status: " + recordStatus + "\n"
                + "Result: " + complianceResult + "\n"
                + "Notes: " + notes;

        txtReportSummary.setText(summary);
        auditRecords.add(summary);

        JOptionPane.showMessageDialog(this,
                complianceResult,
                "Compliance Verification",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while verifying compliance: " + ex.getMessage(),
                "Regulator Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnVerifyComplianceActionPerformed

    private void txtProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIDActionPerformed

    private void txtTrackingRecordIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrackingRecordIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrackingRecordIDActionPerformed

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
    try {
        Regulator regulator = ensureRegulator();

       int productID = parseRequiredInt(txtProductID.getText(), "Product ID");
       int orderID = parseRequiredInt(txtTrackingRecordID.getText(), "Order ID");
       int shipmentID = parseRequiredInt(txtShipmentID.getText(), "Shipment ID");
        String activityType = (String) cmbActivityType.getSelectedItem();
        String recordStatus = (String) cmbRecordStatus.getSelectedItem();
        String auditNotes = readRequiredText(txtAuditNotes.getText(), "Audit Notes");

        Report report = regulator.generateAuditReport();

        String finalReport =
                "Final Regulator Audit Report\n"
                + "================================\n"
                + "Regulator ID: " + regulator.getRegulatorId() + "\n"
                + "Agency Name: " + regulator.getAgencyName() + "\n"
                + "Access Level: " + regulator.getAccessLevel() + "\n"
                + "Audit Region: " + regulator.getAuditRegion() + "\n\n"
                + "Product ID: " + productID + "\n"
                + "Order ID: " + orderID + "\n"
                + "Shipment ID: " + shipmentID + "\n"
                + "Activity Type: " + activityType + "\n"
                + "Record Status: " + recordStatus + "\n\n"
                + "Audit Notes:\n" + auditNotes + "\n\n"
                + "System Report:\n" + report.toString() + "\n\n"
                + "Saved Audit Records: " + auditRecords.size();

        txtReportSummary.setText(finalReport);
        auditRecords.add(finalReport);

        JOptionPane.showMessageDialog(this,
                "Audit report generated successfully.",
                "Generated Report",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while generating report: " + ex.getMessage(),
                "Regulator Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    try {
        LoginGuii loginPage = new LoginGuii();
        loginPage.setVisible(true);
        dispose();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unable to return to login page: " + ex.getMessage(),
                "Navigation Error",
                JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    txtProductID.setText("");
    txtTrackingRecordID.setText("");
    txtShipmentID.setText("");
    txtAuditNotes.setText("");
    txtReportSummary.setText("");

    cmbActivityType.setSelectedIndex(0);
    cmbRecordStatus.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAuditActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuditActivityActionPerformed
    try {
        Regulator regulator = ensureRegulator();

        int productID = parseRequiredInt(txtProductID.getText(), "Product ID");
        int orderID = parseRequiredInt(txtTrackingRecordID.getText(), "Order ID");
        int shipmentID = parseRequiredInt(txtShipmentID.getText(), "Shipment ID");
        String auditNotes = readRequiredText(txtAuditNotes.getText(), "Audit Notes");

        String activityType = (String) cmbActivityType.getSelectedItem();
        String recordStatus = (String) cmbRecordStatus.getSelectedItem();

        regulator.auditSupplyChainActivity();

        String auditRecord =
                "Audit Activity Created\n"
                + "Regulator ID: " + regulator.getRegulatorId() + "\n"
                + "Agency Name: " + regulator.getAgencyName() + "\n"
                + "Audit Region: " + regulator.getAuditRegion() + "\n"
                + "Product ID: " + productID + "\n"
                + "Order ID: " + orderID + "\n"
                + "Shipment ID: " + shipmentID + "\n"
                + "Activity Type: " + activityType + "\n"
                + "Record Status: " + recordStatus + "\n"
                + "Audit Notes: " + auditNotes;

        auditRecords.add(auditRecord);
        txtReportSummary.setText(auditRecord);

        JOptionPane.showMessageDialog(this,
                "Audit activity saved successfully.",
                "Audit Activity",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Unexpected error while auditing activity: " + ex.getMessage(),
                "Regulator Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAuditActivityActionPerformed

    
    private void configureDefaults() {
    txtRegulatorID.setText("");
    txtAgencyName.setText("");
    txtAccessLevel.setText("");
    txtAuditRegion.setText("");

    txtProductID.setText("");
    txtTrackingRecordID.setText("");
    txtShipmentID.setText("");
    txtAuditNotes.setText("");
    txtReportSummary.setText("");

    cmbActivityType.setSelectedIndex(0);
    cmbRecordStatus.setSelectedIndex(0);
}


private void populateFromUserController() {

    try {

        User currentUser = AppContext.getCurrentUser();

        if (currentUser == null) {
            JOptionPane.showMessageDialog(this, "No logged in user found");
            return;
        }

        Connection con = DBConnection.connect();

        String sql = "SELECT * FROM users WHERE user_id=? AND role='Regulator'";

        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, currentUser.getUserID());

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            txtRegulatorID.setText(rs.getString("user_id"));
            txtAgencyName.setText(rs.getString("full_name"));
            txtAccessLevel.setText(rs.getString("role"));

            if (rs.getString("distribution_area") != null) {
                txtAuditRegion.setText(rs.getString("distribution_area"));
            } else {
                txtAuditRegion.setText("Cairo");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Regulator data not found");
        }

        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}


private Regulator ensureRegulator() {
    if (currentRegulator != null) {
        return currentRegulator;
    }

    int regulatorID = parseRequiredInt(txtRegulatorID.getText(), "Regulator ID");
    String agencyName = readRequiredText(txtAgencyName.getText(), "Agency Name");
    String accessLevel = readRequiredText(txtAccessLevel.getText(), "Access Level");
    String auditRegion = readRequiredText(txtAuditRegion.getText(), "Audit Region");

    User baseUser = resolveLoggedInUser();

    if (baseUser != null && regulatorID != baseUser.getUserID()) {
        throw new IllegalArgumentException("Regulator ID must match the logged-in user ID.");
    }

    if (baseUser == null) {
        currentRegulator = new Regulator(
                regulatorID,
                agencyName,
                accessLevel,
                auditRegion,
                regulatorID,
                agencyName,
                "regulator@email.com",
                "password123",
                accessLevel
        );
    } else {
        currentRegulator = new Regulator(
                regulatorID,
                agencyName,
                accessLevel,
                auditRegion,
                baseUser.getUserID(),
                baseUser.getName(),
                baseUser.getEmail(),
                baseUser.getPassword(),
                baseUser.getRole()
        );
    }

    return currentRegulator;
}

private User resolveLoggedInUser() {
    try {
        User currentUser = AppContext.getCurrentUser();

        if (currentUser == null) {
            return null;
        }

        if (userController == null) {
            return currentUser;
        }

        User storedUser = userController.getUser(currentUser.getUserID());
        return storedUser != null ? storedUser : currentUser;

    } catch (Exception ex) {
        return null;
    }
}

private int parseRequiredInt(String value, String fieldName) {
    String text = value == null ? "" : value.trim();

    if (text.isBlank() || text.startsWith("jTextField")) {
        throw new IllegalArgumentException(fieldName + " cannot be empty.");
    }

    if (!text.matches("\\d+")) {
        throw new IllegalArgumentException(fieldName + " must contain numbers only.");
    }

    int number = Integer.parseInt(text);

    if (number <= 0) {
        throw new IllegalArgumentException(fieldName + " must be greater than 0.");
    }

    return number;
}

private String readRequiredText(String value, String fieldName) {
    String text = value == null ? "" : value.trim();

    if (text.isBlank() || text.startsWith("jTextField")) {
        throw new IllegalArgumentException(fieldName + " cannot be empty.");
    }

    return text;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regulator_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regulator_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regulator_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regulator_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regulator_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccessLevel;
    private javax.swing.JLabel AgencyName;
    private javax.swing.JLabel RegulatorID;
    private javax.swing.JButton ReviewStorageConditions;
    private javax.swing.JButton btnAuditActivity;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnVerifyCompliance;
    private javax.swing.JButton btnViewTracking;
    private javax.swing.JComboBox<String> cmbActivityType;
    private javax.swing.JComboBox<String> cmbRecordStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtAccessLevel;
    private javax.swing.JTextField txtAgencyName;
    private javax.swing.JTextArea txtAuditNotes;
    private javax.swing.JTextField txtAuditRegion;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtRegulatorID;
    private javax.swing.JTextArea txtReportSummary;
    private javax.swing.JTextField txtShipmentID;
    private javax.swing.JTextField txtTrackingRecordID;
    // End of variables declaration//GEN-END:variables
}
